### ISSUE TITLE
searching for sha256 hashes 

### ISSUE THREAD

**Issue by kmille** [Debian/debsources#67]
Hey,
I'm looking for an endpoint where I can search for sha256 hashes. It looks like the feature it's only available for copyright files. Is that true and what's the reason for it? It looks like it's on purpose.

debsources is a really nice tool. But the description of the api on the website could be a bit more verbose. You could also link to this repo.

```bash
kmille@linbox:app fd routes.py
copyright/routes.py
doc/routes.py
patches/routes.py
sources/routes.py
```

Thank you!

**Comment by df7cb** [comment]
Perhaps https://archive.softwareheritage.org/api/ ?

**Comment by matthieucan** [comment]
Apologies for the delay, you can also use debsources for SHA-256 searches: https://sources.debian.org/doc/api/
For example https://sources.debian.org/api/sha256/?checksum=d20ad7990610153b563c52681da860b8302afcf0778f75237f8815c07d05141f&page=1

> debsources is a really nice tool. But the description of the api on the website could be a bit more verbose. You could also link to this repo.

That's fair, pull requests are certainly welcome ;)

**Comment by matthieucan** [comment]
> It looks like the feature it's only available for copyright files. Is that true and what's the reason for it? It looks like it's on purpose.

I realize the example I provided is indeed a copyright file, but the search certainly works for all files!

**Comment by kmille** [comment]
So, I have a linux kernel file and I want to check the integrity of that file. After checking the whole internet to find the proper deb file, I don't know what to do...

```bash
kmille@linbox:/mnt sudo md5sum vmlinuz-5.15.0-60-generic
2b3a7df9625421d190cc20e298e8e56e  vmlinuz-5.15.0-60-generic
```
> but the search certainly works for all files!

Can you tell me how?

**Comment by df7cb** [comment]
debsources works on source files, not on the build results.

Try https://dedup.debian.net/ for tat.
